# Generated by Django 5.1 on 2025-06-13 11:08

import ckeditor_uploader.fields
import django.db.models.deletion
import mptt.fields
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kartinka_cat', models.FileField(blank=True, upload_to='Telega/', verbose_name='картинка телеграмма')),
                ('title', models.CharField(max_length=355, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL категории')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='id канала')),
                ('chat_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='url канала')),
                ('chat', models.CharField(blank=True, max_length=100, null=True, verbose_name='канал')),
                ('description_chat', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание канала')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание категории')),
                ('activ', models.BooleanField(default=False, verbose_name='Активно')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Blog.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'app_categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique_for_date='created', verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='ПОСТ для ТЕЛЕГРАММА')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Основной текст')),
                ('kartinka', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Превью поста')),
                ('video', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Видео')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Черновик')], default='draft', max_length=10, verbose_name='Статус поста')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('telegram_posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Время публикации в Телеге')),
                ('fixed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='Blog.category', verbose_name='Категория')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_posts', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'app_posts',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_comment', models.CharField(max_length=80, verbose_name='Автор комментария')),
                ('content', models.TextField(max_length=3000, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Blog.post', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'app_comments',
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='app_categor_title_122f20_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-fixed', '-created', 'status'], name='app_posts_fixed_b5bb97_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created', 'updated', 'active'], name='app_comment_created_e5b4a7_idx'),
        ),
    ]
