# Generated by Django 5.1 on 2025-06-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_category_created_category_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vk_posted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время публикации в VK'),
        ),
    ]
