# Generated by Django 5.0.8 on 2025-10-14 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comment_is_admin_reply_comment_level_comment_lft_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created', 'status'], name='app_posts_created_2a73fb_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug', 'created'], name='app_posts_slug_0b39fc_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', 'status'], name='app_posts_categor_41a828_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created'], name='app_posts_author__7e384c_idx'),
        ),
    ]
