# Generated by Django 5.0.8 on 2025-11-19 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_post_app_posts_created_2a73fb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Blog.post', verbose_name='Статья')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лайк статьи',
                'verbose_name_plural': 'Лайки статей',
                'db_table': 'app_post_likes',
                'indexes': [models.Index(fields=['post', 'user'], name='app_post_li_post_id_8dd216_idx'), models.Index(fields=['post', 'ip_address'], name='app_post_li_post_id_993691_idx')],
            },
        ),
    ]
