# Generated by Django 5.0.8 on 2025-11-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_post_likes_count_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Основное ключевое слово для SEO оптимизации', max_length=50, verbose_name='Главное ключевое слово'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Если не указано, будет использовано описание или первые слова контента', max_length=160, verbose_name='Meta Description (до 160 символов)'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Ключевые слова через запятую (автогенерируются из тегов и контента)', verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Если не указано, будет использован заголовок статьи', max_length=60, verbose_name='Meta Title (до 60 символов)'),
        ),
        migrations.AddField(
            model_name='post',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Отдельное изображение для Open Graph. Если не указано, используется превью поста', null=True, upload_to='seo/', verbose_name='OG Image (для соцсетей)'),
        ),
        migrations.AddField(
            model_name='post',
            name='seo_score',
            field=models.IntegerField(default=0, help_text='Кэшированный SEO score (0-100), обновляется автоматически', verbose_name='SEO Score'),
        ),
    ]
