# Generated by Django 5.0.8 on 2025-11-19 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_add_seo_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(verbose_name='Ответ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='Blog.post', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'FAQ для статьи',
                'verbose_name_plural': 'FAQ для статей',
                'db_table': 'app_post_faqs',
                'ordering': ['order', 'created'],
                'indexes': [models.Index(fields=['post', 'order'], name='app_post_fa_post_id_94b869_idx')],
            },
        ),
    ]
