# Generated by Django 5.0.8 on 2025-11-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_add_post_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='faq_data',
            field=models.JSONField(blank=True, help_text='FAQ блок в формате JSON для structured data', null=True, verbose_name='FAQ блок (JSON)'),
        ),
        migrations.AddField(
            model_name='post',
            name='news_source_url',
            field=models.URLField(blank=True, help_text='URL статьи-источника, на основе которой создана эта статья', max_length=500, null=True, verbose_name='URL источника новостей'),
        ),
        migrations.AddField(
            model_name='post',
            name='parsed_content',
            field=models.TextField(blank=True, help_text='Первоначальный контент (100-200 слов), спарсенный из источника новостей', null=True, verbose_name='Спарсенный контент из новостей'),
        ),
    ]
