# Generated by Django 5.0.8 on 2026-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_category_blog_category_tree_id_lft_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Пустое — из описания/контента. При сохранении убирается markdown/HTML, длина обрезается до 160.', max_length=160, verbose_name='Meta Description (до 160 символов)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.TextField(blank=True, help_text='Через запятую. Оставьте пустым — заполнятся из тегов, контента и заголовка при сохранении.', verbose_name='Meta Keywords'),
        ),
    ]
