# Generated by Django 5.0.8 on 2026-03-31 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_post_vk_wall_post_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='Blog_category_tree_id_lft_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='Blog_comment_tree_id_lft_idx',
        ),
    ]
