# Generated by Django 5.0.8 on 2026-04-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_post_max_posted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tree_id', 'lft'], name='Blog_category_tree_id_lft_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tree_id', 'lft'], name='Blog_comment_tree_id_lft_idx'),
        ),
    ]
