# Generated by Django 5.0.8 on 2026-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_restore_mptt_tree_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите MP4 видео для автовоспроизведения в ленте. Если видео загружено, оно будет показано вместо картинки (ВК, MAX, Блог).', null=True, upload_to='videos/', verbose_name='Видео-файл (вместо превью)'),
        ),
    ]
