# Generated by Django 5.1 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0017_post_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(
                blank=True,
                help_text='Если не указано, будет использован заголовок статьи (в выдаче режется ~60 знаков).',
                max_length=200,
                verbose_name='Meta Title',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.CharField(
                blank=True,
                help_text='Пустое — из описания/контента. В сниппете поиска обычно ~160 знаков.',
                max_length=512,
                verbose_name='Meta Description',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='focus_keyword',
            field=models.CharField(
                blank=True,
                help_text='Основное ключевое слово для SEO оптимизации',
                max_length=200,
                verbose_name='Главное ключевое слово',
            ),
        ),
    ]
