# Generated by Django 5.0.1 on 2026-04-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0018_alter_post_title_and_seo_field_lengths'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='Blog_category_tree_id_lft_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='Blog_comment_tree_id_lft_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Для meta description', max_length=500, null=True, verbose_name='SEO Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Для тега <title>', max_length=255, null=True, verbose_name='SEO Заголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание категории'),
        ),
    ]
