# Generated by Django 5.1.6 on 2026-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_remove_category_blog_category_tree_id_lft_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['tree_id', 'lft'], name='Blog_category_tree_id_lft_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['tree_id', 'lft'], name='Blog_comment_tree_id_lft_idx'),
        ),
    ]
