# Generated by Django 5.1 on 2025-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Имя')),
                ('firma', models.CharField(blank=True, max_length=250, verbose_name='Компания')),
                ('foto', models.FileField(blank=True, upload_to='otzivs', verbose_name='Ваше фото')),
                ('body', models.TextField(blank=True, verbose_name='Текст отзыва')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Отзывы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Rabota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.FileField(blank=True, upload_to='rabotas', verbose_name='Скриншот')),
                ('adres', models.CharField(max_length=200, verbose_name='адрес URL')),
                ('body', models.TextField(blank=True, default='Сайт чмстый код Python фреймворк Django ', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'работы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='home_rabota_name_5e9b93_idx')],
            },
        ),
    ]
