# Generated by Django 5.0.8 on 2025-07-12 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabota',
            name='category',
            field=models.CharField(
                choices=[
                    ('website', 'Сайт'),
                    ('bot', 'Бот'),
                    ('app', 'Приложение'),
                    ('shop', 'Магазин'),
                    ('other', 'Другое')
                ],
                default='website',
                max_length=20,
                verbose_name='Категория'
            ),
        ),
        migrations.AddField(
            model_name='rabota',
            name='technologies',
            field=models.TextField(
                blank=True,
                help_text='Python, Django, React, PostgreSQL и т.д.',
                verbose_name='Использованные технологии'
            ),
        ),
        migrations.AddField(
            model_name='rabota',
            name='status',
            field=models.CharField(
                choices=[
                    ('completed', 'Завершен'),
                    ('in_progress', 'В разработке'),
                    ('maintenance', 'На поддержке')
                ],
                default='completed',
                max_length=20,
                verbose_name='Статус проекта'
            ),
        ),
        migrations.AddField(
            model_name='rabota',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name='Дата создания'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rabota',
            name='updated',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='Дата обновления'
            ),
        ),
        migrations.AddField(
            model_name='rabota',
            name='featured',
            field=models.BooleanField(
                default=False,
                verbose_name='Рекомендуемый проект'
            ),
        ),
        migrations.AddField(
            model_name='rabota',
            name='order',
            field=models.PositiveIntegerField(
                default=0,
                verbose_name='Порядок отображения'
            ),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='adres',
            field=models.URLField(
                blank=True,
                help_text='Ссылка на живой проект',
                max_length=500,
                verbose_name='URL проекта'
            ),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='body',
            field=models.TextField(
                blank=True,
                default='Современный веб-сайт на Python Django с адаптивным дизайном',
                verbose_name='Описание проекта'
            ),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Рекомендуемый размер: 800x600px',
                upload_to='rabotas',
                verbose_name='Скриншот проекта'
            ),
        ),
        migrations.AlterField(
            model_name='rabota',
            name='name',
            field=models.CharField(
                max_length=200,
                verbose_name='Название проекта'
            ),
        ),
        migrations.AlterModelOptions(
            name='rabota',
            options={
                'ordering': ['order', '-created'],
                'verbose_name': 'Работа',
                'verbose_name_plural': 'Работы'
            },
        ),
        migrations.AddIndex(
            model_name='rabota',
            index=models.Index(fields=['category'], name='home_rabota_category_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='rabota',
            index=models.Index(fields=['status'], name='home_rabota_status_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='rabota',
            index=models.Index(fields=['featured'], name='home_rabota_featured_123456_idx'),
        ),
    ]
