# Generated by Django 5.0.8 on 2025-07-12 21:54

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20250712_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtzivComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=80, verbose_name='Имя автора')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Email автора')),
                ('author_company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('content', models.TextField(max_length=3000, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_admin_reply', models.BooleanField(default=False, verbose_name='Ответ администратора')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Комментарий к отзыву',
                'verbose_name_plural': 'Комментарии к отзывам',
                'db_table': 'otziv_comments',
                'ordering': ['-created'],
            },
        ),
        migrations.RenameIndex(
            model_name='rabota',
            new_name='home_rabota_categor_3d5bf7_idx',
            old_name='home_rabota_category_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='rabota',
            new_name='home_rabota_status_21b63c_idx',
            old_name='home_rabota_status_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='rabota',
            new_name='home_rabota_feature_d7bdb8_idx',
            old_name='home_rabota_featured_123456_idx',
        ),
        migrations.AddField(
            model_name='otzivcomment',
            name='otziv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.otziv', verbose_name='Отзыв'),
        ),
        migrations.AddField(
            model_name='otzivcomment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.otzivcomment', verbose_name='Родительский комментарий'),
        ),
        migrations.AddIndex(
            model_name='otzivcomment',
            index=models.Index(fields=['-created', 'updated', 'active'], name='otziv_comme_created_597c02_idx'),
        ),
    ]
