# Generated by Django 5.0.8 on 2025-07-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactmessage_attachment_contactmessage_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.CharField(max_length=200, unique=True, verbose_name='URL страницы')),
                ('title', models.CharField(max_length=60, verbose_name='Title (до 60 символов)')),
                ('description', models.CharField(max_length=160, verbose_name='Description (до 160 символов)')),
                ('keywords', models.TextField(blank=True, verbose_name='Keywords')),
                ('og_title', models.CharField(blank=True, max_length=60, verbose_name='OG Title')),
                ('og_description', models.CharField(blank=True, max_length=160, verbose_name='OG Description')),
                ('og_image', models.ImageField(blank=True, upload_to='seo/', verbose_name='OG Image')),
                ('canonical_url', models.URLField(blank=True, verbose_name='Canonical URL')),
                ('h1', models.CharField(blank=True, max_length=100, verbose_name='H1 заголовок')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'SEO настройки',
                'verbose_name_plural': 'SEO настройки',
                'ordering': ['page_url'],
            },
        ),
    ]
