# Generated by Django 5.0.8 on 2025-07-13 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_seomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'Главная секция'), ('about', 'О нас'), ('resume', 'Услуги'), ('portfolio', 'Портфолио'), ('testimonials', 'Отзывы'), ('blog', 'Блог'), ('contact', 'Контакты')], max_length=20, unique=True, verbose_name='Секция')),
                ('background_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('gradient', 'Градиент')], default='image', max_length=10, verbose_name='Тип фона')),
                ('background_image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 1920x1080px', null=True, upload_to='section_backgrounds/', verbose_name='Фоновое изображение')),
                ('background_video', models.FileField(blank=True, help_text='Формат: MP4, WebM. Размер: до 50MB', null=True, upload_to='section_backgrounds/videos/', verbose_name='Фоновое видео')),
                ('gradient_start', models.CharField(default='#3b82f6', help_text='Формат: #RRGGBB', max_length=7, verbose_name='Начальный цвет градиента')),
                ('gradient_end', models.CharField(default='#8b5cf6', help_text='Формат: #RRGGBB', max_length=7, verbose_name='Конечный цвет градиента')),
                ('gradient_direction', models.CharField(choices=[('to-r', 'Вправо'), ('to-l', 'Влево'), ('to-t', 'Вверх'), ('to-b', 'Вниз'), ('to-tr', 'Вправо-вверх'), ('to-tl', 'Влево-вверх'), ('to-br', 'Вправо-вниз'), ('to-bl', 'Влево-вниз')], default='to-br', max_length=20, verbose_name='Направление градиента')),
                ('overlay_opacity', models.IntegerField(default=0, help_text='0-100, где 0 - без наложения, 100 - полностью темный', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прозрачность наложения')),
                ('overlay_color', models.CharField(default='#000000', help_text='Формат: #RRGGBB', max_length=7, verbose_name='Цвет наложения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Фон секции',
                'verbose_name_plural': 'Фоны секций',
                'ordering': ['section'],
            },
        ),
    ]
