# Generated by Django 5.0.8 on 2025-07-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_service_extraservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaloneExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.CharField(blank=True, help_text='Например: от 15,000 ₽/мес', max_length=50, verbose_name='Цена')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга',
                'verbose_name_plural': 'Дополнительные услуги',
                'db_table': 'home_standalone_extraservice',
                'ordering': ['order'],
            },
        ),
        migrations.AlterModelOptions(
            name='extraservice',
            options={'ordering': ['order'], 'verbose_name': 'Дополнительная услуга в составе', 'verbose_name_plural': 'Дополнительные услуги в составе'},
        ),
        migrations.AlterModelTable(
            name='extraservice',
            table='home_service_extraservice',
        ),
    ]
