# Generated by Django 5.0.8 on 2025-07-13 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_standaloneextraservice_alter_extraservice_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сессии')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='Номер заказа')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email клиента')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('processing', 'В обработке'), ('confirmed', 'Подтвержден'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус заказа')),
                ('payment_status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты')], default='pending', max_length=20, verbose_name='Статус оплаты')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='order_files/%Y/%m/%d/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Название файла')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание файла')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='home.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Файл заказа',
                'verbose_name_plural': 'Файлы заказов',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('service', 'Основная услуга'), ('extra_service', 'Дополнительная услуга')], max_length=20, verbose_name='Тип услуги')),
                ('service_id', models.PositiveIntegerField(verbose_name='ID услуги')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
            },
        ),
        migrations.CreateModel(
            name='OrderQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, verbose_name='Название проекта')),
                ('project_description', models.TextField(blank=True, verbose_name='Описание проекта')),
                ('target_audience', models.TextField(blank=True, verbose_name='Целевая аудитория')),
                ('competitors', models.TextField(blank=True, verbose_name='Конкуренты')),
                ('technical_requirements', models.TextField(blank=True, verbose_name='Технические требования')),
                ('design_preferences', models.TextField(blank=True, verbose_name='Предпочтения по дизайну')),
                ('functionality_requirements', models.TextField(blank=True, verbose_name='Требования к функциональности')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Желаемый срок сдачи')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='Диапазон бюджета')),
                ('additional_requirements', models.TextField(blank=True, verbose_name='Дополнительные требования и пожелания')),
                ('preferred_contact_method', models.CharField(blank=True, max_length=50, verbose_name='Предпочтительный способ связи')),
                ('additional_contacts', models.TextField(blank=True, verbose_name='Дополнительные контакты')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire', to='home.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Опросный лист',
                'verbose_name_plural': 'Опросные листы',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('service', 'Основная услуга'), ('extra_service', 'Дополнительная услуга')], max_length=20, verbose_name='Тип услуги')),
                ('service_id', models.PositiveIntegerField(verbose_name='ID услуги')),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.cart', verbose_name='Корзина')),
            ],
            options={
                'verbose_name': 'Элемент корзины',
                'verbose_name_plural': 'Элементы корзины',
                'unique_together': {('cart', 'service_type', 'service_id')},
            },
        ),
    ]
