# Generated by Django 5.0.8 on 2025-07-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cart_order_orderfile_orderitem_orderquestionnaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID платежа YooKassa'),
        ),
    ]
