# Generated by Django 5.0.8 on 2025-07-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_order_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='order_files/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='orderfile',
            name='filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название файла'),
        ),
    ]
