# Generated by Django 5.0.8 on 2025-10-14 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_customer_order_customer_ordercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True, verbose_name='Ключ сессии')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('essential_cookies', models.BooleanField(default=True, verbose_name='Обязательные cookie')),
                ('analytics_cookies', models.BooleanField(default=False, verbose_name='Аналитические cookie')),
                ('marketing_cookies', models.BooleanField(default=False, verbose_name='Маркетинговые cookie')),
                ('consent_given', models.BooleanField(default=False, verbose_name='Согласие дано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Согласие на cookie',
                'verbose_name_plural': 'Согласия на cookie',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.order', verbose_name='Заказ'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-created', 'is_read'], name='home_contac_created_d29a67_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email', 'created'], name='home_contac_email_aa9274_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['ip_address', '-created'], name='home_contac_ip_addr_176ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='home_order_order_n_41122d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created'], name='home_order_custome_a7cf6a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'status'], name='home_order_payment_c23f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created'], name='home_order_created_64ee75_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_id'], name='home_order_payment_87dd2e_idx'),
        ),
        migrations.AddIndex(
            model_name='otziv',
            index=models.Index(fields=['-created', 'active'], name='home_otziv_created_2a2ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='rabota',
            index=models.Index(fields=['category', 'status'], name='home_rabota_categor_2b4b6c_idx'),
        ),
        migrations.AddIndex(
            model_name='rabota',
            index=models.Index(fields=['-created', 'status'], name='home_rabota_created_734529_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['session_key'], name='home_cookie_session_c2ab90_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['ip_address', '-created'], name='home_cookie_ip_addr_e18a2d_idx'),
        ),
    ]
