# Generated by Django 5.0.8 on 2025-11-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_cookieconsent_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ООО "ЛукИнтерЛаб"', max_length=255, verbose_name='Название компании')),
                ('company_full_name', models.CharField(default='Общество с ограниченной ответственностью "ЛукИнтерЛаб"', max_length=500, verbose_name='Полное наименование')),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, default='г. Москва, ул. Ярославская, д. 9', verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('phone', models.CharField(default='+7-905-856-02-82', max_length=50, verbose_name='Телефон')),
                ('email', models.CharField(default='Ya@LukyanovSY.ru', max_length=100, verbose_name='Email')),
                ('website', models.URLField(default='https://lukinterlab.ru', verbose_name='Сайт')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Название банка')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Расчётный счёт')),
                ('correspondent_account', models.CharField(blank=True, max_length=20, verbose_name='Корреспондентский счёт')),
                ('bik', models.CharField(blank=True, max_length=9, verbose_name='БИК')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='legal_docs/', verbose_name='Договор')),
                ('extract_file', models.FileField(blank=True, null=True, upload_to='legal_docs/', verbose_name='Выписка из ЕГРЮЛ')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='legal_docs/', verbose_name='Сертификат Минцифры')),
                ('about_site', models.TextField(blank=True, help_text='Информация о сайте и его назначении', verbose_name='О сайте')),
                ('about_company', models.TextField(blank=True, help_text='Подробная информация о компании', verbose_name='О компании')),
                ('terms_of_use', models.TextField(blank=True, verbose_name='Условия использования')),
                ('privacy_policy', models.TextField(blank=True, verbose_name='Политика конфиденциальности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Правовая информация',
                'verbose_name_plural': 'Правовая информация',
                'ordering': ['-updated'],
            },
        ),
    ]
