# Generated by Django 5.0.8 on 2025-11-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_legalinfo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='seomodel',
            index=models.Index(fields=['page_url'], name='home_seomod_page_ur_be267f_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active', 'order'], name='home_servic_is_acti_f43d75_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='home_servic_is_acti_2b8c39_idx'),
        ),
        migrations.AddIndex(
            model_name='standaloneextraservice',
            index=models.Index(fields=['is_active', 'order'], name='home_standa_is_acti_cba504_idx'),
        ),
        migrations.AddIndex(
            model_name='standaloneextraservice',
            index=models.Index(fields=['is_active'], name='home_standa_is_acti_254fd5_idx'),
        ),
    ]
