# Generated by Django 5.0.8 on 2026-03-25 19:39

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabota',
            name='history_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Описание процесса создания и развития проекта', verbose_name='История развития'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='instructions_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Руководство пользователя или примеры использования', verbose_name='Инструкции'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='parameters_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Спецификации, архитектура, нагрузки', verbose_name='Технические параметры'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='resources_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Список использованных ресурсов (команда, время, ассеты)', verbose_name='Ресурсы'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='tariffs_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='Стоимость разработки или тарифные планы', verbose_name='Тарифы'),
        ),
        migrations.AddIndex(
            model_name='otzivcomment',
            index=models.Index(fields=['tree_id', 'lft'], name='home_otzivcomment_tree_id_97b1'),
        ),
    ]
