# Generated by Django 5.0.8 on 2026-03-25 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rabota_history_text_rabota_instructions_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RabotaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rabota_media/', verbose_name='Файл (Изображение или Видео)')),
                ('is_video', models.BooleanField(default=False, verbose_name='Это видео')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rabota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='home.rabota', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Медиафайл проекта',
                'verbose_name_plural': 'Медиафайлы проекта',
                'ordering': ['order', 'created'],
            },
        ),
    ]
