# Generated by Django 5.0.8 on 2026-03-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_rabotamedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otziv',
            options={'ordering': ['-created'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
