# Generated by Django 5.0.8 on 2026-03-31 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_otziv_options'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='otzivcomment',
            name='home_otzivcomment_tree_id_97b1',
        ),
    ]
