# Generated by Django 5.0.8 on 2026-04-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_otzivcomment_home_otzivcomment_tree_id_97b1'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otzivcomment',
            index=models.Index(fields=['tree_id', 'lft'], name='home_otzivcomment_tree_id_97b1'),
        ),
    ]
