# Generated by Django 5.0.8 on 2026-04-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_sitemarketingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemarketingsettings',
            name='body_end_html',
            field=models.TextField(blank=True, help_text='Доп. скрипты, вторичные пиксели.', verbose_name='Перед закрытием &lt;/body&gt;'),
        ),
        migrations.AlterField(
            model_name='sitemarketingsettings',
            name='google_tag_body_html',
            field=models.TextField(blank=True, verbose_name='Google Tag Manager (noscript сразу после &lt;body&gt;)'),
        ),
        migrations.AlterField(
            model_name='sitemarketingsettings',
            name='google_tag_head_html',
            field=models.TextField(blank=True, verbose_name='Google Tag Manager / аналитика (часть для &lt;head&gt;)'),
        ),
        migrations.AlterField(
            model_name='sitemarketingsettings',
            name='head_extra_html',
            field=models.TextField(blank=True, help_text='Проверка сайта, пиксели и т.п.', verbose_name='Дополнительно в &lt;head&gt;'),
        ),
        migrations.AlterField(
            model_name='sitemarketingsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitemarketingsettings',
            name='yandex_metrika_html',
            field=models.TextField(blank=True, help_text='Если заполнено и включена подмена — выводится вместо встроенного счётчика в шаблоне.', verbose_name='Яндекс.Метрика и счётчики (фрагмент для &lt;head&gt; или полный)'),
        ),
    ]
