# Generated by Django 5.1 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_sitemarketingsettings_body_end_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seomodel',
            name='description',
            field=models.CharField(
                max_length=512,
                verbose_name='Description (meta, в выдаче режется ~160 знаков)',
            ),
        ),
        migrations.AlterField(
            model_name='seomodel',
            name='og_description',
            field=models.CharField(
                blank=True,
                max_length=512,
                verbose_name='OG Description',
            ),
        ),
        migrations.AlterField(
            model_name='seomodel',
            name='og_title',
            field=models.CharField(
                blank=True,
                max_length=200,
                verbose_name='OG Title',
            ),
        ),
        migrations.AlterField(
            model_name='seomodel',
            name='title',
            field=models.CharField(
                max_length=200,
                verbose_name='Title (meta / до ~60 знаков в выдаче)',
            ),
        ),
    ]
