# Generated by Django 5.1.6 on 2026-04-07 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rabota_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (число)'),
        ),
        migrations.AddField(
            model_name='extraservice',
            name='price_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (число)'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (число)'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='Основное ключевое слово', max_length=100, verbose_name='Focus Keyword'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Описание для поисковиков', max_length=500, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, verbose_name='Meta Keywords'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Заголовок для поисковиков', max_length=255, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_rabotas', to='home.service', verbose_name='Связанная услуга/тариф'),
        ),
        migrations.AddField(
            model_name='rabota',
            name='seo_score',
            field=models.IntegerField(default=0, help_text='Оценка оптимизации (0-100)', verbose_name='SEO Score'),
        ),
        migrations.AddField(
            model_name='service',
            name='price_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Числовое значение для расчетов.', max_digits=12, null=True, verbose_name='Цена (число)'),
        ),
        migrations.AddField(
            model_name='standaloneextraservice',
            name='price_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена (число)'),
        ),
        migrations.AlterField(
            model_name='extraservice',
            name='price',
            field=models.CharField(blank=True, help_text='Например: от 15,000 ₽/мес', max_length=50, verbose_name='Цена (текст)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(blank=True, help_text='Например: от 50,000 ₽. Если заполнено числовое поле ниже, это поле будет игнорироваться.', max_length=50, verbose_name='Цена (текст)'),
        ),
        migrations.AlterField(
            model_name='standaloneextraservice',
            name='price',
            field=models.CharField(blank=True, help_text='Например: от 15,000 ₽/мес', max_length=50, verbose_name='Цена (текст)'),
        ),
    ]
