# Generated by Django 5.1.6 on 2026-04-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rabota_sale_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemarketingsettings',
            name='google_tag_head_html',
            field=models.TextField(blank=True, help_text='Выводится при включённом «Включить вывод с БД».', verbose_name='Google (gtag.js или GTM) — фрагмент для &lt;head&gt;'),
        ),
        migrations.AlterField(
            model_name='sitemarketingsettings',
            name='replace_builtin_counters',
            field=models.BooleanField(default=False, help_text='Не используется: в base.html больше нет захардкоженных GTM/Метрики. Счётчики только из полей выше.', verbose_name='Устарело: замена встроенных счётчиков'),
        ),
        migrations.AlterField(
            model_name='sitemarketingsettings',
            name='yandex_metrika_html',
            field=models.TextField(blank=True, help_text='При включённом «Включить вывод с БД» выводится в &lt;head&gt;.', verbose_name='Яндекс.Метрика и счётчики (фрагмент для &lt;head&gt; или полный)'),
        ),
    ]
