# Generated by Django 5.0.8 on 2025-11-19 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Blog', '0006_post_likes_count_postlike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModerationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора критериев')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('criteria', models.JSONField(default=dict, help_text='JSON с критериями: forbidden_words, min_length, max_length, spam_patterns, tone_rules', verbose_name='Критерии модерации')),
                ('actions', models.JSONField(default=dict, help_text='JSON с действиями: delete, correct, reply', verbose_name='Действия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Критерий модерации комментариев',
                'verbose_name_plural': 'Критерии модерации комментариев',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ModerationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора критериев')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('criteria', models.JSONField(default=dict, help_text='JSON с критериями: min_length, max_length, required_keywords, forbidden_words, tone, structure', verbose_name='Критерии модерации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Критерий модерации статей',
                'verbose_name_plural': 'Критерии модерации статей',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CommentModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('approved', 'Одобрено'), ('deleted', 'Удалено'), ('corrected', 'Исправлено'), ('replied', 'Ответ добавлен')], max_length=20, null=True, verbose_name='Действие')),
                ('check_results', models.JSONField(default=dict, verbose_name='Результаты проверки')),
                ('corrected_text', models.TextField(blank=True, verbose_name='Исправленный текст')),
                ('auto_reply', models.TextField(blank=True, verbose_name='Автоматический ответ')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='Проверено')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Промодерировано')),
                ('comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='Blog.comment', verbose_name='Комментарий')),
                ('criteria_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Moderation.commentmoderationcriteria', verbose_name='Использованные критерии')),
            ],
            options={
                'verbose_name': 'Модерация комментария',
                'verbose_name_plural': 'Модерация комментариев',
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['action', '-checked_at'], name='Moderation__action_d46e4f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает модерации'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('needs_revision', 'Требует доработки')], default='pending', max_length=20, verbose_name='Статус модерации')),
                ('check_results', models.JSONField(default=dict, help_text='Детальные результаты проверки по каждому критерию', verbose_name='Результаты проверки')),
                ('moderator_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено на модерацию')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Промодерировано')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_articles', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='Blog.post', verbose_name='Статья')),
                ('criteria_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Moderation.moderationcriteria', verbose_name='Использованные критерии')),
            ],
            options={
                'verbose_name': 'Модерация статьи',
                'verbose_name_plural': 'Модерация статей',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', '-submitted_at'], name='Moderation__status_4c67ad_idx'), models.Index(fields=['moderator', '-moderated_at'], name='Moderation__moderat_1d6615_idx')],
            },
        ),
        migrations.CreateModel(
            name='SEOAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, help_text='До 60 символов', max_length=60, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='До 160 символов', max_length=160, verbose_name='Meta Description')),
                ('focus_keyword', models.CharField(blank=True, max_length=100, verbose_name='Фокусное ключевое слово')),
                ('seo_score', models.IntegerField(default=0, help_text='Оценка от 0 до 100', verbose_name='SEO Score')),
                ('analysis_data', models.JSONField(default=dict, help_text='Детальные результаты SEO анализа', verbose_name='Данные анализа')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='Проанализировано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_analysis', to='Blog.post', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'SEO анализ',
                'verbose_name_plural': 'SEO анализы',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['seo_score', '-analyzed_at'], name='Moderation__seo_sco_a75bea_idx')],
            },
        ),
    ]
