# Generated by Django 5.0.8 on 2025-11-19 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('articles_pending', models.IntegerField(default=0, verbose_name='Статей на модерации')),
                ('articles_approved', models.IntegerField(default=0, verbose_name='Одобрено статей')),
                ('articles_rejected', models.IntegerField(default=0, verbose_name='Отклонено статей')),
                ('articles_needs_revision', models.IntegerField(default=0, verbose_name='Требует доработки')),
                ('comments_pending', models.IntegerField(default=0, verbose_name='Комментариев на модерации')),
                ('comments_approved', models.IntegerField(default=0, verbose_name='Одобрено комментариев')),
                ('comments_deleted', models.IntegerField(default=0, verbose_name='Удалено комментариев')),
                ('comments_corrected', models.IntegerField(default=0, verbose_name='Исправлено комментариев')),
                ('seo_analyzed', models.IntegerField(default=0, verbose_name='Проанализировано статей')),
                ('seo_avg_score', models.FloatField(default=0, verbose_name='Средний SEO score')),
                ('seo_high_score', models.IntegerField(default=0, verbose_name='Высокий score (80+)')),
                ('seo_low_score', models.IntegerField(default=0, verbose_name='Низкий score (<50)')),
                ('avg_moderation_time', models.FloatField(default=0, verbose_name='Среднее время модерации (часы)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статистика модерации',
                'verbose_name_plural': 'Статистика модерации',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date'], name='Moderation__date_4bafe1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('article_pending', 'Статья ожидает модерации'), ('comment_pending', 'Комментарий ожидает модерации'), ('article_approved', 'Статья одобрена'), ('article_rejected', 'Статья отклонена'), ('seo_low_score', 'Низкий SEO score')], max_length=20, verbose_name='Тип уведомления')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('article_moderation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Moderation.articlemoderation', verbose_name='Модерация статьи')),
                ('comment_moderation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Moderation.commentmoderation', verbose_name='Модерация комментария')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('seo_analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Moderation.seoanalysis', verbose_name='SEO анализ')),
            ],
            options={
                'verbose_name': 'Уведомление модератора',
                'verbose_name_plural': 'Уведомления модераторов',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created'], name='Moderation__recipie_fb1313_idx')],
            },
        ),
    ]
