# Generated by Django 5.0.8 on 2025-11-19 15:11

import django.db.models.deletion
from django.db import migrations, models


def migrate_comment_data(apps, schema_editor):
    """Перенос данных из старого поля comment в GenericForeignKey"""
    CommentModeration = apps.get_model('Moderation', 'CommentModeration')
    ContentTypeModel = apps.get_model('contenttypes', 'ContentType')

    # На чистой БД строки в django_content_type для Blog.comment ещё может не быть
    # (post_migrate создаёт их позже), поэтому get, а не get_or_create, падал с DoesNotExist.
    comment_ct, _ = ContentTypeModel.objects.using(schema_editor.connection.alias).get_or_create(
        app_label='Blog',
        model='comment',
    )
    
    # Переносим данные - в момент миграции старое поле comment еще существует
    # Используем прямое обращение через comment_id (ForeignKey поле)
    db_alias = schema_editor.connection.alias
    
    for moderation in CommentModeration.objects.using(db_alias).all():
        # В старой версии модели есть поле comment (OneToOneField к Comment)
        # Доступ через comment_id - ID связанного комментария
        comment_id = moderation.comment_id if hasattr(moderation, 'comment_id') else None
        
        if comment_id:
            moderation.content_type = comment_ct
            moderation.object_id = comment_id
            moderation.comment_type = 'blog.comment'
            moderation.save(using=db_alias)


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_post_likes_count_postlike'),
        ('Moderation', '0002_moderationstatistics_moderationnotification'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        # Сначала добавляем новые поля
        migrations.AddField(
            model_name='commentmoderation',
            name='comment_type',
            field=models.CharField(choices=[('blog.comment', 'Комментарий к статье'), ('home.otzivcomment', 'Комментарий к отзыву'), ('home.ordercomment', 'Комментарий к заказу')], default='blog.comment', max_length=50, verbose_name='Тип комментария'),
        ),
        migrations.AddField(
            model_name='commentmoderation',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип комментария'),
        ),
        migrations.AddField(
            model_name='commentmoderation',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID комментария'),
        ),
        # Переносим данные из старого поля comment в новые поля content_type/object_id
        migrations.RunPython(migrate_comment_data, migrations.RunPython.noop),
        # Добавляем индексы
        migrations.AddIndex(
            model_name='commentmoderation',
            index=models.Index(fields=['content_type', 'object_id'], name='Moderation__content_e1ae6d_idx'),
        ),
        migrations.AddIndex(
            model_name='commentmoderation',
            index=models.Index(fields=['comment_type', '-checked_at'], name='Moderation__comment_350acf_idx'),
        ),
        # Устанавливаем unique_together
        migrations.AlterUniqueTogether(
            name='commentmoderation',
            unique_together={('content_type', 'object_id')},
        ),
        # Удаляем старое поле
        migrations.RemoveField(
            model_name='commentmoderation',
            name='comment',
        ),
    ]
