# Generated by Django 5.1 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moderation', '0004_commentmoderation_action_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationnotification',
            name='title',
            field=models.CharField(max_length=512, verbose_name='Заголовок'),
        ),
    ]
