# Generated by Django 4.2.7 on 2025-10-06 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('services', 'Услуги'), ('pricing', 'Ценообразование'), ('contacts', 'Контакты'), ('faq', 'Часто задаваемые вопросы'), ('company', 'О компании'), ('technical', 'Техническая поддержка')], max_length=20, verbose_name='Категория')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('keywords', models.TextField(help_text='Ключевые слова через запятую', verbose_name='Ключевые слова')),
                ('priority', models.IntegerField(default=1, verbose_name='Приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'База знаний',
                'verbose_name_plural': 'База знаний',
                'ordering': ['-priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Включен')),
                ('welcome_message', models.TextField(default='Привет! Я виртуальный ассистент LukInterLab. Чем могу помочь?', verbose_name='Приветственное сообщение')),
                ('ai_model', models.CharField(default='gpt-3.5-turbo', max_length=50, verbose_name='AI модель')),
                ('max_tokens', models.IntegerField(default=1000, verbose_name='Максимум токенов')),
                ('temperature', models.FloatField(default=0.7, verbose_name='Температура')),
                ('auto_start', models.BooleanField(default=False, verbose_name='Автозапуск')),
                ('show_typing_indicator', models.BooleanField(default=True, verbose_name='Показывать индикатор печати')),
                ('enable_voice', models.BooleanField(default=False, verbose_name='Голосовое управление')),
                ('theme_color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет темы')),
                ('position', models.CharField(choices=[('bottom-right', 'Правый нижний'), ('bottom-left', 'Левый нижний')], default='bottom-right', max_length=20, verbose_name='Позиция')),
                ('max_messages_per_session', models.IntegerField(default=50, verbose_name='Максимум сообщений в сессии')),
                ('session_timeout', models.IntegerField(default=30, verbose_name='Таймаут сессии (минуты)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки ассистента',
                'verbose_name_plural': 'Настройки ассистента',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100, unique=True, verbose_name='ID сессии')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('page_url', models.URLField(blank=True, verbose_name='URL страницы')),
                ('referrer', models.URLField(blank=True, verbose_name='Источник перехода')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сессия чата',
                'verbose_name_plural': 'Сессии чата',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент'), ('system', 'Система')], max_length=20, verbose_name='Тип сообщения')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Использовано токенов')),
                ('response_time', models.FloatField(default=0, verbose_name='Время ответа (сек)')),
                ('model_used', models.CharField(blank=True, max_length=50, verbose_name='Использованная модель')),
                ('is_helpful', models.BooleanField(blank=True, null=True, verbose_name='Полезно ли сообщение')),
                ('user_feedback', models.TextField(blank=True, verbose_name='Отзыв пользователя')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Assistant.chatsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ChatAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('total_sessions', models.IntegerField(default=0, verbose_name='Всего сессий')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Всего сообщений')),
                ('unique_users', models.IntegerField(default=0, verbose_name='Уникальных пользователей')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='Среднее время ответа')),
                ('satisfaction_rate', models.FloatField(default=0, verbose_name='Процент удовлетворенности')),
            ],
            options={
                'verbose_name': 'Аналитика чата',
                'verbose_name_plural': 'Аналитика чата',
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
