# Generated by Django 4.2.7 on 2025-10-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsettings',
            name='ai_provider',
            field=models.CharField(choices=[('gigachat', 'GigaChat'), ('openai', 'OpenAI')], default='gigachat', max_length=20, verbose_name='AI провайдер'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='gigachat_client_id',
            field=models.CharField(blank=True, help_text='Client ID для авторизации в GigaChat', max_length=255, verbose_name='GigaChat Client ID'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='gigachat_client_secret',
            field=models.TextField(blank=True, help_text='Client Secret для авторизации в GigaChat (хранится в зашифрованном виде)', verbose_name='GigaChat Client Secret'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='gigachat_scope',
            field=models.CharField(choices=[('GIGACHAT_API_PERS', 'Для физических лиц'), ('GIGACHAT_API_CORP', 'Для юридических лиц')], default='GIGACHAT_API_PERS', max_length=100, verbose_name='GigaChat Scope'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='gigachat_verify_ssl_certs',
            field=models.BooleanField(default=True, help_text='Рекомендуется включить для продакшена', verbose_name='Проверять SSL сертификаты'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='openai_api_key',
            field=models.TextField(blank=True, help_text='API ключ OpenAI (хранится в зашифрованном виде)', verbose_name='OpenAI API Key'),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='ai_model',
            field=models.CharField(default='GigaChat:latest', help_text='Для GigaChat: GigaChat:latest, GigaChat:latest-long, GigaChat:latest-rag', max_length=50, verbose_name='AI модель'),
        ),
    ]
