# Generated by Django 4.2.7 on 2025-10-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0002_assistantsettings_ai_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantsettings',
            name='gigachat_scope',
            field=models.CharField(default='GIGACHAT_API_PERS', help_text='Scope для доступа к GigaChat API (например: GIGACHAT_API_PERS)', max_length=100, verbose_name='GigaChat Scope'),
        ),
    ]
