# Generated by Django 4.2.7 on 2025-10-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0003_alter_assistantsettings_gigachat_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsettings',
            name='assistant_name',
            field=models.CharField(default='Сергей', max_length=50, verbose_name='Имя ассистента'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='auto_start_delay',
            field=models.IntegerField(default=3, help_text='Через сколько секунд после загрузки страницы показать приветствие', verbose_name='Задержка автозапуска (секунды)'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='enable_admin_takeover',
            field=models.BooleanField(default=False, help_text='Позволить администратору перехватывать диалог через Telegram', verbose_name='Разрешить перехват диалога администратором'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='enable_telegram_notifications',
            field=models.BooleanField(default=False, help_text='Отправлять уведомления администратору о новых сообщениях', verbose_name='Включить уведомления в Telegram'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='telegram_admin_chat_id',
            field=models.CharField(blank=True, help_text='ID чата администратора в Telegram', max_length=50, verbose_name='Telegram Chat ID администратора'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='telegram_bot_token',
            field=models.TextField(blank=True, help_text='Токен бота для уведомлений администратора (хранится в зашифрованном виде)', verbose_name='Telegram Bot Token'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='use_personalized_greeting',
            field=models.BooleanField(default=True, help_text='Использовать имя пользователя в приветствии', verbose_name='Персонализированное приветствие'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='welcome_message_template',
            field=models.TextField(default='Доброго дня! Чем можем быть полезны? Я Ассистент {name}, готов ответить на Ваши вопросы. Сейчас действует скидка 30% на сайты с интеграцией AI. Интересно?', help_text='Используйте {name} для имени ассистента, {username} для имени пользователя', verbose_name='Шаблон приветственного сообщения'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='admin_user_id',
            field=models.CharField(blank=True, help_text='ID пользователя Telegram, который управляет диалогом', max_length=50, verbose_name='ID администратора'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_admin_controlled',
            field=models.BooleanField(default=False, help_text='True если диалог перехвачен администратором', verbose_name='Управляется администратором'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='telegram_message_id',
            field=models.CharField(blank=True, help_text='ID последнего сообщения в Telegram чате', max_length=50, verbose_name='ID сообщения в Telegram'),
        ),
    ]
