# Generated by Django 4.2.7 on 2025-10-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0004_assistantsettings_assistant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsettings',
            name='gigachat_authorization_key',
            field=models.TextField(blank=True, help_text='Ключ авторизации для GigaChat API (хранится в зашифрованном виде). Получите в личном кабинете Studio.', verbose_name='GigaChat Authorization Key'),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='gigachat_client_id',
            field=models.CharField(blank=True, help_text='Устаревшее поле. Используйте Authorization Key.', max_length=255, verbose_name='GigaChat Client ID (deprecated)'),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='gigachat_client_secret',
            field=models.TextField(blank=True, help_text='Устаревшее поле. Используйте Authorization Key.', verbose_name='GigaChat Client Secret (deprecated)'),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='gigachat_scope',
            field=models.CharField(default='GIGACHAT_API_PERS', help_text='Scope для доступа к GigaChat API (GIGACHAT_API_PERS для физ.лиц, GIGACHAT_API_CORP для юр.лиц)', max_length=100, verbose_name='GigaChat Scope'),
        ),
    ]
