# Generated by Django 4.2.7 on 2025-10-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0005_add_gigachat_authorization_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantsettings',
            name='gigachat_scope',
            field=models.CharField(choices=[('GIGACHAT_API_PERS', 'Для физических лиц'), ('GIGACHAT_API_B2B', 'Для ИП и юр.лиц (платные пакеты)'), ('GIGACHAT_API_CORP', 'Для ИП и юр.лиц (pay-as-you-go)')], default='GIGACHAT_API_PERS', help_text='Scope для доступа к GigaChat API', max_length=100, verbose_name='GigaChat Scope'),
        ),
    ]
