# Generated by Django 4.2.7 on 2025-10-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0006_update_gigachat_scope_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantsettings',
            name='ai_model',
            field=models.CharField(default='GigaChat', help_text='Для GigaChat: GigaChat, GigaChat-Pro, GigaChat-Max, GigaChat-Plus и др.', max_length=50, verbose_name='AI модель'),
        ),
    ]
