# Generated by Django 5.0.8 on 2025-11-18 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0007_update_default_model'),
        ('Blog', '0005_post_app_posts_created_2a73fb_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название шаблона')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('title_prompt', models.TextField(help_text='Промпт для генерации заголовка статьи. Используйте {topic}, {category} для подстановки значений.', verbose_name='Промпт для заголовка')),
                ('description_prompt', models.TextField(help_text='Промпт для генерации описания статьи для Telegram. Используйте {title}, {content} для подстановки.', verbose_name='Промпт для описания (Telegram)')),
                ('content_prompt', models.TextField(help_text='Промпт для генерации основного текста статьи. Используйте {topic}, {category}, {keywords} для подстановки.', verbose_name='Промпт для основного контента')),
                ('image_prompt', models.TextField(blank=True, help_text='Промпт для генерации изображения через GigaChat-Pro. Используйте {title}, {topic} для подстановки.', verbose_name='Промпт для генерации изображения (GigaChat-Pro)')),
                ('default_tags', models.CharField(blank=True, help_text='Теги через запятую, которые будут добавлены к статье', max_length=500, verbose_name='Теги по умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompt_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('default_category', models.ForeignKey(blank=True, help_text='Категория, которая будет использоваться, если не указана в расписании', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.category', verbose_name='Категория по умолчанию')),
            ],
            options={
                'verbose_name': 'Шаблон промпта',
                'verbose_name_plural': 'Шаблоны промптов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AISchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название расписания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('frequency', models.CharField(choices=[('hourly', 'Каждый час'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('custom', 'Произвольное (CRON)')], default='daily', max_length=20, verbose_name='Частота генерации')),
                ('cron_expression', models.CharField(blank=True, help_text='Используется только для частоты "Произвольное". Формат: минута час день месяц день_недели', max_length=100, verbose_name='CRON выражение')),
                ('articles_per_run', models.IntegerField(default=1, help_text='Количество статей, которые будут сгенерированы за один запуск', verbose_name='Статей за раз')),
                ('tags', models.CharField(blank=True, help_text='Теги через запятую, которые будут добавлены к статье', max_length=500, verbose_name='Теги')),
                ('keywords', models.TextField(blank=True, help_text='Ключевые слова для генерации контента, через запятую', verbose_name='Ключевые слова')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные в формате JSON, которые будут переданы в промпты. Например: {"topic": "красота", "tone": "дружелюбный"}', verbose_name='Дополнительные данные')),
                ('text_model', models.CharField(default='GigaChat', help_text='Модель GigaChat для генерации текста (обычная модель)', max_length=50, verbose_name='Модель для текста')),
                ('image_model', models.CharField(default='GigaChat-Pro', help_text='Модель GigaChat для генерации изображений (PRO модель)', max_length=50, verbose_name='Модель для изображений')),
                ('use_image_generation', models.BooleanField(default=False, help_text='Использовать GigaChat-Pro для генерации изображений вместо загрузки из источников', verbose_name='Генерировать изображения')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Следующий запуск')),
                ('total_generated', models.IntegerField(default=0, verbose_name='Всего сгенерировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(blank=True, help_text='Категория для статей. Если не указана, используется из шаблона.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.category', verbose_name='Категория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('prompt_template', models.ForeignKey(help_text='Шаблон промпта, который будет использоваться для генерации', on_delete=django.db.models.deletion.CASCADE, to='Assistant.prompttemplate', verbose_name='Шаблон промпта')),
            ],
            options={
                'verbose_name': 'Расписание генерации',
                'verbose_name_plural': 'Расписания генерации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_title', models.TextField(verbose_name='Сгенерированный заголовок')),
                ('generated_description', models.TextField(blank=True, verbose_name='Сгенерированное описание')),
                ('generated_content', models.TextField(verbose_name='Сгенерированный контент')),
                ('generated_image_prompt', models.TextField(blank=True, verbose_name='Промпт для изображения')),
                ('title_prompt_used', models.TextField(verbose_name='Использованный промпт для заголовка')),
                ('description_prompt_used', models.TextField(blank=True, verbose_name='Использованный промпт для описания')),
                ('content_prompt_used', models.TextField(verbose_name='Использованный промпт для контента')),
                ('image_prompt_used', models.TextField(blank=True, verbose_name='Использованный промпт для изображения')),
                ('ai_title_response', models.TextField(blank=True, verbose_name='Ответ AI для заголовка')),
                ('ai_description_response', models.TextField(blank=True, verbose_name='Ответ AI для описания')),
                ('ai_content_response', models.TextField(blank=True, verbose_name='Ответ AI для контента')),
                ('ai_image_response', models.TextField(blank=True, verbose_name='Ответ AI для изображения')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Контекст генерации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('generation_time', models.FloatField(blank=True, null=True, verbose_name='Время генерации (сек)')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Использовано токенов')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated', to='Blog.post', verbose_name='Статья')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_articles', to='Assistant.aischedule', verbose_name='Расписание')),
                ('prompt_template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Assistant.prompttemplate', verbose_name='Использованный шаблон')),
            ],
            options={
                'verbose_name': 'Сгенерированная статья',
                'verbose_name_plural': 'Сгенерированные статьи',
                'ordering': ['-created_at'],
            },
        ),
    ]
