# Generated by Django 5.0.8 on 2025-11-18 19:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0008_prompttemplate_aischedule_aigeneratedarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='Токены промпта')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='Токены ответа')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Всего токенов')),
                ('cost', models.DecimalField(decimal_places=4, default=0, help_text='Рассчитывается на основе тарифов GigaChat', max_digits=10, verbose_name='Стоимость (руб)')),
                ('requests_count', models.IntegerField(default=0, verbose_name='Количество запросов')),
            ],
            options={
                'verbose_name': 'Использование токенов',
                'verbose_name_plural': 'Использование токенов',
                'ordering': ['-date', 'model'],
                'indexes': [models.Index(fields=['-date', 'model'], name='Assistant_t_date_c5b7ec_idx'), models.Index(fields=['date'], name='Assistant_t_date_30ee7a_idx')],
                'unique_together': {('date', 'model')},
            },
        ),
    ]
