# Generated by Django 5.0.8 on 2025-11-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0009_tokenusage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenusage',
            name='cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='При подписке стоимость = 0', max_digits=10, verbose_name='Стоимость (руб)'),
        ),
    ]
