# Generated by Django 5.0.8 on 2025-11-18 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0010_alter_tokenusage_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompttemplate',
            name='description_prompt',
        ),
    ]
