# Generated by Django 5.0.8 on 2025-11-20 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0011_remove_prompttemplate_description_prompt'),
        ('Blog', '0009_post_faq_data_post_news_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='faq_prompt',
            field=models.TextField(blank=True, help_text='Промпт для генерации FAQ блока. Используйте {title}, {content} для подстановки. Формат ответа: JSON массив [{"question": "...", "answer": "..."}]', verbose_name='Промпт для генерации FAQ блока'),
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=500, verbose_name='URL источника')),
                ('source_name', models.CharField(max_length=200, verbose_name='Название источника')),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('api', 'API'), ('scraping', 'Веб-скрапинг')], default='rss', max_length=50, verbose_name='Тип источника')),
                ('total_views', models.IntegerField(default=0, verbose_name='Общее количество просмотров')),
                ('articles_count', models.IntegerField(default=0, verbose_name='Количество использованных статей')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='Последнее использование')),
                ('rating', models.FloatField(default=0.0, verbose_name='Рейтинг источника')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Источник новостей',
                'verbose_name_plural': 'Источники новостей',
                'ordering': ['-rating', '-last_used'],
                'indexes': [models.Index(fields=['-rating', 'is_active'], name='Assistant_n_rating_b36979_idx'), models.Index(fields=['source_type'], name='Assistant_n_source__125d94_idx')],
                'unique_together': {('source_url', 'source_name')},
            },
        ),
        migrations.CreateModel(
            name='CategoryStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.IntegerField(default=0, verbose_name='Общее количество просмотров')),
                ('articles_count', models.IntegerField(default=0, verbose_name='Количество статей')),
                ('last_publication', models.DateTimeField(blank=True, null=True, verbose_name='Последняя публикация')),
                ('priority', models.FloatField(default=1.0, verbose_name='Приоритет категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='Blog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статистика категории',
                'verbose_name_plural': 'Статистика категорий',
                'ordering': ['-priority', '-last_publication'],
                'indexes': [models.Index(fields=['-priority', 'last_publication'], name='Assistant_c_priorit_7f3506_idx')],
            },
        ),
    ]
