# Generated by Django 5.0.8 on 2025-11-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0012_prompttemplate_faq_prompt_newssource_categorystats'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='content_generation_mode',
            field=models.CharField(choices=[('generate', 'Генерация основного текста статьи на основании промпта'), ('parse_and_generate', 'Поиск и парсинг 200 слов из интернета + генерация основного текста'), ('full_parse', 'Полный парсинг основного текста статьи в полном объёме как у источника')], default='generate', help_text='Способ получения основного контента статьи', max_length=20, verbose_name='Режим генерации контента'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='image_generation_mode',
            field=models.CharField(choices=[('generate', 'Генерация на основании промпта из image_prompt'), ('search_and_parse', 'Искать и парсить изображение на основании запроса')], default='generate', help_text='Способ получения изображения для статьи', max_length=20, verbose_name='Режим генерации изображения'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='image_search_criteria',
            field=models.TextField(blank=True, help_text='Критерии для поиска и парсинга изображения (используется при режиме "Искать и парсить")', verbose_name='Критерий поиска изображения'),
        ),
    ]
