# Generated by Django 5.0.8 on 2025-11-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0013_add_generation_modes_to_prompt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='generate_content',
            field=models.BooleanField(default=True, help_text='Включить генерацию основного текста статьи', verbose_name='Генерировать основной текст'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='generate_faq',
            field=models.BooleanField(default=True, help_text='Включить генерацию FAQ блока (вопросы-ответы)', verbose_name='Генерировать FAQ блок'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='generate_image',
            field=models.BooleanField(default=True, help_text='Включить генерацию/поиск изображения для статьи', verbose_name='Генерировать изображение'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='generate_tags',
            field=models.BooleanField(default=True, help_text='Включить автоматическую генерацию тегов', verbose_name='Генерировать теги'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='generate_title',
            field=models.BooleanField(default=True, help_text='Включить генерацию заголовка статьи', verbose_name='Генерировать заголовок'),
        ),
    ]
