# Generated by Django 5.0.8 on 2025-11-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0014_add_generation_toggles_to_prompt_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompttemplate',
            name='faq_prompt',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='generate_faq',
        ),
        migrations.RemoveField(
            model_name='prompttemplate',
            name='generate_tags',
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='additional_section_prompt',
            field=models.TextField(blank=True, help_text='Промпт для генерации дополнительного блока. Используйте {title}, {content}, {category}, {keywords} для подстановки. Примеры: FAQ блок, мотивационные слоганы, TO-DO задачи, таблица содержания. Результат должен быть в формате HTML.', verbose_name='Промпт для дополнительной секции'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='generate_additional_section',
            field=models.BooleanField(default=False, help_text='Включить генерацию дополнительного блока после основного текста (FAQ, слоганы, TO-DO, таблица содержания и т.д.)', verbose_name='Генерировать дополнительную секцию'),
        ),
    ]
