# Generated by Django 5.0.8 on 2025-11-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0015_add_additional_section_remove_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='content_prompt',
            field=models.TextField(blank=True, help_text='Промпт для генерации основного текста статьи. Используйте {topic}, {category}, {keywords} для подстановки.', verbose_name='Промпт для основного контента'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='title_prompt',
            field=models.TextField(blank=True, help_text='Промпт для генерации заголовка статьи. Используйте {topic}, {category} для подстановки значений.', verbose_name='Промпт для заголовка'),
        ),
    ]
