# Generated by Django 5.0.8 on 2025-11-21 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0016_make_prompts_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigeneratedarticle',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_articles', to='Assistant.aischedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='gigachat_verify_ssl_certs',
            field=models.BooleanField(default=False, help_text='Рекомендуется включить для продакшена. Можно переопределить через GIGACHAT_VERIFY_SSL в settings.py', verbose_name='Проверять SSL сертификаты'),
        ),
    ]
