# Generated by Django 5.0.8 on 2025-11-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assistant', '0017_alter_aigeneratedarticle_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsettings',
            name='subscription_token_limits',
            field=models.JSONField(blank=True, default=dict, help_text='JSON объект с лимитами токенов для каждой модели. Пример: {"GigaChat-2-Max": 50000, "GigaChat-2-Pro": 44400}. Если пусто, используются значения по умолчанию из TOKEN_LIMITS.', verbose_name='Лимиты токенов подписки'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='image_model',
            field=models.CharField(default='GigaChat-2-Pro', help_text='Модель GigaChat для генерации изображений. Pro или Max поддерживают генерацию изображений', max_length=50, verbose_name='Модель для изображений'),
        ),
        migrations.AlterField(
            model_name='aischedule',
            name='text_model',
            field=models.CharField(default='GigaChat-2-Lite', help_text='Модель GigaChat для генерации текста. Рекомендации: Lite - простые задачи, Pro - сбалансированная, Max - сложные задачи', max_length=50, verbose_name='Модель для текста'),
        ),
    ]
